services:
  pccf:
    container_name: pccf
    build: .
    volumes:
      - ../PCCF:/home/PCCF
    # Por defecto, mantener el contenedor vivo para modo detached
    command: tail -f /dev/null
    # Variables de entorno útiles
    environment:
      - TERM=xterm-256color
    # Configuración TTY para modo interactivo
    tty: true
    stdin_open: true
